@echo off

set fp=%~dp1
set fn=%~n1

echo Deleting autogenerated files...
rmdir "%fp%obj\" /s /q

echo Creating output folder...
mkdir "%fp%obj\"

echo Compiling...
ca65 --cpu 65816 -o "%fp%obj\%fn%.o" "%fp%%fn%.s"

echo Linking...
ld65 -C "%fp%memmap.cfg" -o "%fp%obj\%fn%.smc" "%fp%obj\%fn%.o"
